apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-test
spec:
  containers:
    - name: client
      image: python:3.10
      command: ["/bin/sh", "-c"]
      args:
        - |
          apt update && apt install -y python3-pip;
          pip install pika;
          sleep 3600
      volumeMounts:
        - name: test-scripts
          mountPath: /scripts
  volumes:
    - name: test-scripts
      configMap:
        name: rabbitmq-test-scripts
